name: Automation_scala_ReusableJobCluster
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: automationscalareusablejobcluster
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-01-24 05:06:07'
pipelines:
  pipelines/Automation_scala_ReusableJobCluster_Pipeline:
    name: Automation_scala_ReusableJobCluster_Pipeline
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-01-24 05:07:01'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/dAWtdk8h_team_147/maAl0ym9_project_168.git&subPath=&tag=scala_project/v2&projectSubscriptionProjectId=168&path=datasets/dataset_cust_in
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/Automation_scala_ReusableJobCluster_Schedule:
    name: Automation_scala_ReusableJobCluster_Schedule
    description: ''
    fabricUID: 604
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: adv-json2
    scheduleCron: 0 0 0 1/1 * ? 2090
    timeout: null
    alerting:
      emails: abhisheks+e2etests@prophecy.io
      onStart: true
      onSuccess: false
      onFailure: true
    pipelines:
    - pipelines/Automation_scala_ReusableJobCluster_Pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-01-24 05:10:49'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-01-24 05:06:07'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-01-24T05:06:07.460243Z'
  name: plibMaven
  version: 8.7.0
  id: '2049386828'
  createdAt: '2025-01-24T05:06:07.460243Z'
  type: plibMaven
projectDependencies:
  '1':
    projectUID: 1
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/XIUGo8J6_team_2/XIUGo8J6_project_1.git&subPath=
    version: 0.2.6
    isDefault: true
    author: null
    createdAt: '2025-01-24 05:05:53'
  '2':
    projectUID: 2
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/XIUGo8J6_team_2/XIUGo8J6_project_2.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-01-24 05:05:53'
  '168':
    projectUID: 168
    projectName: scala_project
    repositoryPath: gitUri=http://gitserver:3000/dAWtdk8h_team_147/maAl0ym9_project_168.git&subPath=
    version: scala_project/v2
    isDefault: false
    author: null
    createdAt: '2025-01-24 05:05:53'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
