name: Automation_python_ReusableJobCluster
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: automationpythonreusablejobcluster
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-07-11 06:19:16'
pipelines:
  pipelines/Automation_python_ReusableJobCluster_Pipeline:
    name: Automation_python_ReusableJobCluster_Pipeline
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-07-11 06:20:13'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/dAWtdk8h_team_147/Ln6aHaI0_project_169.git&subPath=&tag=python_project/v1&projectSubscriptionProjectId=169&path=datasets/dataset_cust_in
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/Automation_python_ReusableJobCluster_Schedule:
    name: Automation_python_ReusableJobCluster_Schedule
    description: ''
    fabricUID: 1567
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: adv-json2
    scheduleCron: 0 0 0 1/1 * ? 2090
    timeout: null
    alerting:
      emails: abhisheks+e2etests@prophecy.io
      onStart: true
      onSuccess: false
      onFailure: true
    pipelines:
    - pipelines/Automation_python_ReusableJobCluster_Pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-07-11 06:24:27'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-11 06:19:16'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-07-11T06:19:16.0446Z'
  name: plibMaven
  version: 8.10.1
  id: '1595743167'
  createdAt: '2025-07-11T06:19:16.0446Z'
  type: plibMaven
- modifiedAt: '2025-07-11T06:19:16.0446Z'
  name: plibPypi
  version: 1.9.49
  id: '1002977308'
  createdAt: '2025-07-11T06:19:16.0446Z'
  type: plibPypi
projectDependencies:
  '4':
    projectUID: 4
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/XIUGo8J6_team_2/XIUGo8J6_project_4.git&subPath=
    version: 0.2.46
    isDefault: true
    author: null
    createdAt: '2025-07-11 06:19:00'
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/XIUGo8J6_team_2/XIUGo8J6_project_5.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-07-11 06:19:00'
  '169':
    projectUID: 169
    projectName: python_project
    repositoryPath: gitUri=http://gitserver:3000/dAWtdk8h_team_147/Ln6aHaI0_project_169.git&subPath=
    version: python_project/v1
    isDefault: false
    author: null
    createdAt: '2025-07-11 06:19:00'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
